spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Bug-Tracker
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
email:
  sender: your-email@gmail.com
